# Generated by Django 4.1.1 on 2022-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='pin',
        ),
        migrations.AlterField(
            model_name='pin',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
