# Generated by Django 4.1.1 on 2022-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_alter_pin_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
