# Generated by Django 3.2.7 on 2022-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_remove_pin_pin_alter_pin_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('valid', 'valid'), ('invalid', 'invalid')], default='valid', max_length=20),
        ),
        migrations.AddField(
            model_name='pin',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
