# Generated by Django 4.1.1 on 2022-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_pin_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
