# Generated by Django 3.2.7 on 2022-10-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_auto_20221006_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
