# Generated by Django 4.1.1 on 2022-11-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_alter_pin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='batch',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='location',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
    ]
