# Generated by Django 3.2.7 on 2022-10-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_pin_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='amount',
        ),
    ]
