# Generated by Django 3.2.7 on 2022-10-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0005_remove_pin_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pin.caller'),
        ),
    ]
