# Generated by Django 4.1.1 on 2022-11-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0005_pin_batch_alter_pin_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='batch',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
