# Generated by Django 3.2.7 on 2022-10-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0006_pin_caller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caller',
            name='user',
        ),
    ]
