# Generated by Django 4.1.1 on 2022-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0006_alter_pin_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='batch',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
