# Generated by Django 4.1.1 on 2023-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0007_alter_pin_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='management',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
