# Generated by Django 4.1.1 on 2022-10-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0007_remove_caller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('valid', 'UNUSED'), ('invalid', 'USED')], default='valid', max_length=20),
        ),
    ]
