# Generated by Django 4.1.1 on 2022-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0008_alter_pin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='secret',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
