# Generated by Django 4.1.1 on 2022-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0009_alter_pin_pin_alter_pin_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
